@startuml
'https://plantuml.com/sequence-diagram

class App {
+main()

+String wantCSS
+String wantJS
}
App <--o WebsiteGenerator

WebsiteGenerator : +String siteName
WebsiteGenerator : +String author
WebsiteGenerator : +String path
WebsiteGenerator : +String createWebsite()
WebsiteGenerator : +String createJSFolder()
WebsiteGenerator : +String createCSSFolder()
WebsiteGenerator : +String createHTML()

@enduml